version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: suvapdatabase
    container_name: suvap
    volumes:
      - ./postgres:/var/lib/postgresql/data
